id: P000596
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:49:27.223890
source_metadata:
  id: bdr:W1AC439
  title: 'ངལ་རྩོལ་སྐོར་གྱི་རྩོད་གླེང་། '
  author: ''
  volumes:
    82cec137884e4e9dabd87bc75a33b953:
      image_group_id: I2PD18828
      title: ''
      volume_number: 1
      total_pages: 270
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
