id: P000596
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC439
  title: 'ངལ་རྩོལ་སྐོར་གྱི་རྩོད་གླེང་། '
  author: ''
  volumes:
    82cec137884e4e9dabd87bc75a33b953:
      image_group_id: I2PD18828
      title: ''
      volume_number: 1
      total_pages: 270
